# run in container
sudo: false

# install dependencies
# addons:
#  apt:
#    packages:
#    - libboost-all-dev
  

# we compile a c++ project
language: cpp

# test with gcc and clang
compiler:
  - gcc
#  - clang
env:
  global:
    - PATH=/usr/lib/ccache:${PATH}
  matrix:
    - DIM=1;2;3
      #- DIM=2
      #- DIM=3 
cache: ccache
# prepare compilation  
before_script:
  - git clone https://www.github.com/UG4/ughub
  - ughub/ughub init
  - ughub/ughub install ugcore LuaShell
  - mkdir build && cd build && cmake ../ -DTARGET=ugshell -DLAPACK=OFF -DBLAS=OFF -DDIM="${DIM}" -DCOMPILE_INFO=OFF

# compile ug
script: V=1 make -j2
