# run in container
sudo: false

addons:
    apt:
      packages:
       - make
       - cmake-data
       - cmake
  

# we compile a c++ project
language: cpp

compiler:
    - gcc
    - clang

os:
  - linux
  - osx
  
env:
  global:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then PATH=/usr/lib/ccache:${PATH}; fi
    - TIMEOUT_BUILD='30m'
    - BUILD_SUCCESS=true
    
  matrix:
    - DIM=2 CPU=1 TARGET=ugshell STATIC_BUILD=ON
    - DIM=2 CPU=1 TARGET=vrl STATIC_BUILD=OFF
    - DIM=ALL CPU=ALL TARGET=ugshell STATIC_BUILD=ON
    - DIM=ALL CPU=ALL TARGET=vrl STATIC_BUILD=OFF
      
      
cache:
  ccache: true
  directories:
   #- $HOME/Library/Caches/Homebrew
   # TODO: how can we do conditional caching of directories (depending on OS)
   #- /home/travis/build/miho/OCC-CSG/oce-OCE-0.18.3
   #- /Users/travis/build/miho/ugcore/

# prepare compilation  
before_script:
  - mkdir -p travis_root && cd travis_root
  - git clone https://www.github.com/UG4/ughub
  - mkdir ug4 && cd ug4
  - ../ughub/ughub init .
  - ../ughub/ughub install ugcore
  - rm -rf ugcore
  
  - |
     echo "--------------------------------------------------------------------------------"
     echo $TRAVIS_COMMIT
     echo $TRAVIS_TAG
     echo $TRAVIS_BRANCH
     echo $TRAVIS_BUILD_NUMBER
     echo $TRAVIS_REPO_SLUG
     echo "--------------------------------------------------------------------------------"
    
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git ugcore
  - git checkout -qf $TRAVIS_COMMIT
  - mkdir -p build && cd build && cmake ../ -DTARGET="${TARGET}" -DLAPACK=OFF -DBLAS=OFF -DDIM="${DIM}" -DCPU="${CPU}" -DCOMPILE_INFO=OFF -DEMBEDDED_PLUGINS=ON -DSTATIC_BUILD="${STATIC_BUILD}"
  
# compile ug
script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then timeout -s SIGTERM $TIMEOUT_BUILD make -j4 install > install_out.txt || export BUILD_SUCCESS=false ; fi
    - make -j4
    - if [[ "$TARGET" == "ugshell" ]]; then ../bin/ugshell -call "print(\"it works\")"; fi
